http://127.0.0.1:8000/api

###
http://127.0.0.1:8000/api/users

###

http://127.0.0.1:8000/api/users/1

###

POST http://127.0.0.1:8000/api/users
content-type: application/json

{
    "name": "carlos",
    "email": "1234@gmail.com",
    "password": "senha1234"
}


###

PATCH http://127.0.0.1:8000/api/users/1
Content-Type: application/json

{
    "name": "novo nome",
    "email": "novo email"
}

###

DELETE http://127.0.0.1:8000/api/users/1